### ISSUE TITLE
Truncating large long values

### ISSUE THREAD

**Issue by bhavinmdesai** [circlecell/jsonlintdotcom#11]
It is truncating large long values. You can parse the following JSON Object and compare the values

{"large_long_a":288536860722989048,"string":"2013-10-30 03:41:10","large_long_b":288517478611921009}

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com)

**Comment by bhavinmdesai** [comment]
Awesome! Thanks
