### ISSUE TITLE
ES5 JSONValues not linting according to spec.

### ISSUE THREAD

**Issue by sterpe** [circlecell/jsonlintdotcom#15]
All of the following are valid JSON.parses on all major browsers 
      see http://es5.github.io/x15.12.html#x15.12.1.2

`JSON.parse(1)`
`JSON.parse("0")`
`JSON.parse(true)`
`JSON.parse("false")`
`JSON.parse(null)`
`JSON.parse("null")`
`JSON.parse("\"foo\"")`

However all of these are listed as JSONLint errors because they are not wrapped by either `[` or `{`, however this does not seem to be an actual part of the ES5 specification nor do browser native parsers have this requirement.

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com)

**Comment by sterpe** [comment]
+1
