### ISSUE TITLE
Removes duplicate attributes from JSON-LD

### ISSUE THREAD

**Issue by miguel-perez** [circlecell/jsonlintdotcom#16]
JSON-LD allows for having multiple identical attributes. Currently, the linter is removing these attributes.

http://json-ld.org/

**Comment by finom** [comment]
Most of the issues of [jsonlint.com](http://jsonlint.com) are fixed but the app still shows "Valid JSON" (which is actually an issue). Closing for now because the main issue from this topic is fixed.
