### ISSUE TITLE
Jsonlint does not support quotation marks

### ISSUE THREAD

**Issue by facundofarias** [circlecell/jsonlintdotcom#19]
When I put a JSON document that contains quotation marks, it fails (like, for example '”'). If I replace those ones with the normal double quote (like this one '"'), it works perfectly.
Example:
```
{“status”: 200,”name”: 
 “Tanya Anderssen”,
  ”version”: {
     “number”: “1.3.4",
     ”build_hash”: “a70f3ccb52200f8f2c87e9c370c6597448eb3e45",
     ”build_timestamp”: “2014–09–30T09:07:17Z”,
     ”build_snapshot”: false,
     ”lucene_version”: “4.9"},
   ”tagline”: “You Know, for Search”
}
```

Thanks

**Comment by darth-walsh** [comment]
The [JSON spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) is clear that the only valid quote character is the normal one, `"` (U+0022).
Maybe the error message could be improved, but jsonlint is correct that fancy quotations marks `”` aren't valid for JSON strings.

**Comment by facundofarias** [comment]
Right, maybe by improving the error message it's enough. Agreed.

**Comment by finom** [comment]
jsonlint.com now has syntax highlighting so you can see that something goes wrong. Closing this issue, thanks for reporting.

**Comment by facundofarias** [comment]
:+1:
Thanks!
