### ISSUE TITLE
jsonlint removes internal spaces in array values on validating array-as-value bracketed by "s

### ISSUE THREAD

**Issue by dpnewkirk** [circlecell/jsonlintdotcom#22]
If instead of the valid JSON

{
    "key1": [
        "key2",
        "key2 value with spaces"
    ]
}

we instead ask JSONlint to validate

{
    "key1": "[
        "key2",
        "key2 value with spaces"
    ]"
}

we are duly informed that the " before [ is an error, but with that validation we see also that JSONlint has collapsed the value

"key2 value with spaces"

to

"key2valuewithspaces"

--a behavior that's especially hazardous should the JSON snippet under test be sufficiently large and/or complex to disallow our eyes catching the collapse.

Best regards,

David Newkirk

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com). Thanks for reporting.
