### ISSUE TITLE
Lone surrogates in strings shouldn't be pretty printed as literal characters

### ISSUE THREAD

**Issue by darthwalsh** [circlecell/jsonlintdotcom#23]
Lone surrogate code units should be left escaped in the pretty printed JSON, and should not be literally displayed in the browser.

The JSON pretty printer does a good job at deciding when to decode escaped Unicode characters into the literal character and when not to (for example, compare the pretty printing of [`["\u0030"]`](http://jsonlint.com/?json=%5B%22%5Cu0030%22%5D) vs. [`["\u0000"]`](http://jsonlint.com/?json=%5B%22%5Cu0000%22%5D)).

In Chrome, if I validate JSON with a lone surrogate code unit [`["\ud800"]`](http://jsonlint.com/?json=%5B%22%5Cud800%22%5D) I see what looks like:
```
[
    "
]
```

The pretty-printed output should be copy-pastable JSON, but copy-pasting this instead pastes the Unicode Replacement character `�` between quotation marks.

Instead, the above should pretty print as:
```
[
    "\ud800"
]
```

(Amazingly I can copy-paste U+D800 from Internet Explorer into Word, which is pretty impressive considering a lone surrogate isn't a real Unicode code point.)

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com). Thanks for reporting.
