### ISSUE TITLE
Batch validate

### ISSUE THREAD

**Issue by tomturton** [circlecell/jsonlintdotcom#25]
Extremely useful tool, thanks.

Please could you add a facility to batch validate JSON files?

**Comment by circlecell** [comment]
Hi @tomturton can you elaborate on your use case here a bit more? This sounds like a nice idea, but I want to make sure I understand it all the way through. Thank you!

**Comment by finom** [comment]
@circlecell I guess @tomturton means something like D'n'D/form feature where he can choose N files from a computer.

**Comment by tomturton** [comment]
Yes, I think being able to select multiple files to upload and validate would be very valuable. Drag and drop would be a nice way of doing it.

**Comment by BlockWorld** [comment]
+1 SUPPORT, that would indeed be *very* valuable, and drag & drop would be great.

**Comment by circlecell** [comment]
@finom seems as though the call is for drag+drop that allows (potentially) multiple files to simply trigger individual validate calls... so duplication/repeater on the input field. A nice excuse to play with the HTML5 File API :)

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com/#!/batch/) which is based on community requirements. Thank you.
