### ISSUE TITLE
converts "0.0" to "0" after the format

### ISSUE THREAD

**Issue by Zapakmvr** [circlecell/jsonlintdotcom#26]
jsonlint is converting a decimal field having "0.0" to a int "0", please see input output below.

I know technically 0.0 and 0 are equal but that's something my application should handle , Jsonlint should give me output after format as is without any change in its values.

input 
{"Discount":0.0}

output
{
    "Discount": 0
}

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com)
