### ISSUE TITLE
Can I post json string from another site?

### ISSUE THREAD

**Issue by cornernote** [circlecell/jsonlintdotcom#28]
I have a site where people can submit json data which uses php. I can tell the user when it's invalid and link them to lint, but it would be great if I can link them to a pre-populated lint (perhaps via a post request). 

Is there any current way to do this, or do they have to paste the json into lint themselves?

**Comment by finom** [comment]
@cornernote sorry for long response. You can use ``json`` GET parameter for it. A value should be urlencoded. [Example](http://jsonlint.com/?json=%7B%22employees%22%3A%5B%20%20%20%20%7B%22firstName%22%3A%22John%22%2C%20%22lastName%22%3A%22Doe%22%7D%2C%20%20%20%20%7B%22firstName%22%3A%22Anna%22%2C%20%22lastName%22%3A%22Smith%22%7D%2C%20%20%20%20%7B%22firstName%22%3A%22Peter%22%2C%20%22lastName%22%3A%22Jones%22%7D%5D%7D).

**Comment by cornernote** [comment]
Thanks
