### ISSUE TITLE
Upgrade jsonlint parser

### ISSUE THREAD

**Issue by closacco** [circlecell/jsonlintdotcom#3]
Received email feedback:

> JSONLint expects [ or { in a JSON text first. http://zaach.github.io/jsonlint does not and seems to comply to the standard: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

**Comment by IndiegameGarden** [comment]
Indeed confirmed: this JSONLint parser does not accept as input the plain string "true", i.e. without the [ or { characters. While "true" is a valid JSON document according to the ECMA-404 standard as well as IETF RFC 7159 (https://tools.ietf.org/html/rfc7159).

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com)
