### ISSUE TITLE
Quoted strings should be valid JSON format

### ISSUE THREAD

**Issue by pellicano** [circlecell/jsonlintdotcom#31]
Refer to: https://tools.ietf.org/html/rfc7159#page-13

Steps to reproduce:
1. Enter http://jsonlint.com/
2. Type "This is a valid string" and click "Validate".

Expected result: Validation succeeded message.
Actual result: 
"Parse error on line 1:
"anythingisvalid"
^
Expecting '{', '['"

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com). Thanks for reporting.
