### ISSUE TITLE
Page reloads on validate removing results from view

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [circlecell/jsonlintdotcom#33]
To reproduce paste a JSON on http://www.jsonlint.com/
click validate
results flash on screen and are removed upon reload
adding ';return false' to the onclick event makes it work

i have this issue using both firefox and chromium

**Comment by BlockWorld** [comment]
It works for me...

**Comment by GM-Script-Writer-62850** [comment]
just cause i don't want to use youtube...
http://i.imgur.com/kTtOgc5.gif

**Comment by BlockWorld** [comment]
Hm... odd. That definitely does not happen to me.

**Comment by GM-Script-Writer-62850** [comment]
Running this from the scratch pad does make it act correctly
`document.getElementById('JSONValidate').setAttribute('onsubmit','return false');`
i have no idea what is triggering the submit event on the form

**Comment by GM-Script-Writer-62850** [comment]
this also fixes it
`document.getElementById('validate').type='button';`

**Comment by coffeduong** [comment]
It happened to me too. Page reload after I click Validate.
Maybe the author wanna us to try Pro ;)

**Comment by visualcookie** [comment]
Problem is, that u seem to have AdBlock installed. Tried it in incognito mode, where I have no extensions, and it worked.

**Comment by circlecell** [comment]
This should be fixed - we're definitely not interested in things being messed up when AdBlock is installed.
