### ISSUE TITLE
URLdecode and validate

### ISSUE THREAD

**Issue by omidaminiva** [circlecell/jsonlintdotcom#34]
It would be a nice feature to add URL Decode (or other popular decoding like base64) and validate after as separate function

**Comment by BlockWorld** [comment]
+1

**Comment by circlecell** [comment]
Can you articulate the use case a bit more @omidaminiva? I understand what you're saying, but am curious to also understand what it is you're workflow is for this now.

**Comment by omidaminiva** [comment]
when working with a server that encodes all of its JSON responses, I have to use a decoder to decode the response then I can validate it.

**Comment by finom** [comment]
@circlecell what do you think?

**Comment by circlecell** [comment]
@finom yeah, this seems reasonable... perhaps as a toggled setting that saves the preference for the user via cookie/localstorage/etc.

**Comment by finom** [comment]
I had some thoughts and the feature can complicate UX. Closing.
