### ISSUE TITLE
pro.jsonlint.com has a DNS error

### ISSUE THREAD

**Issue by NodexTech** [circlecell/jsonlintdotcom#35]
Hi. 

pro.jsonlint.com has a DNS error, it worked up until a day or two ago!

**Comment by circlecell** [comment]
Yes, we really messed up a registrar switch. The old registrar (Name.com) name servers started redirecting to a domain monetization service, and there was some sort of issue with the pre-setup of DNS at NameCheap (looking into it with them). And, we simply didn't setup pro.jsonint.com. Our fault. It should be OK in a few moments. Thank you for letting us know!
