### ISSUE TITLE
Invalid escape sequence incorrectly validates

### ISSUE THREAD

**Issue by RobT2012** [circlecell/jsonlintdotcom#39]
According to http://json.org/ this is NOT correct yet it validates by jsonlint
{    "test": "\" }

It also incorrectly validates other invalid escape sequences.
Example, this is not a valid JSON escape sequence but it validates
{    "test": "\h" }

**Comment by finom** [comment]
@RobT2012 thanks.

I don't think this is invalid

```js
{ "test": "\h" }
```

**Comment by RobT2012** [comment]
@finom 

It's always best to refer to the official documentation. You can review the http://json.org/ flow chart and also read the RFC, ECMA docs, there's definitely no path for a \ followed by a the character h, it's rather clear there's a very specific set of valid escape char sequences that must be followed,  the only path for undefined syntax is to reject the JSON as invalid.

**Comment by RobT2012** [comment]
FYI: I was alerted to the escape sequence problem by a colleague who was using jsonlint.com, he was arguing with me that the JSON library I am using was incorrectly rejecting his supposedly valid JSON strings.

You can try the cases I presented with other on-line validators, including JSON libs for C/C++ etc, they will (should) all reject the examples I gave, however it does not matter what anyone says or thinks, what matters is what the official JSON specifications dictate, in this case there's no room for interpretation that I can see.

**Comment by finom** [comment]
@RobT2012 hmm, OK. It sounds like we need to make our own linter instead of using jsonlint.

**Comment by finom** [comment]
It was my fault :(
