### ISSUE TITLE
Submitted URI too large! (localhost - xampp)

### ISSUE THREAD

**Issue by noxidsoft** [circlecell/jsonlintdotcom#40]
## http://localhost/jsonlint/?code=%5B%7B%22created_at%22%3A%22Wed+Jan+27+04%3A55%...

Submitted URI too large!

The length of the requested URL exceeds the capacity limit for this server. The request cannot be processed.

If you think this is a server error, please contact the webmaster.

Error 414

localhost
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30

**Comment by finom** [comment]
Thanks.

**Comment by finom** [comment]
Not actual, closing.

**Comment by manoj1991** [comment]
I suppose you have submitted a large form with GET request. There are some limits for this, and the exact character limits are depending on browser and the webserver you are using.

You should consider using POST requests.
