### ISSUE TITLE
Add support for sending the json as a query string parameter 

### ISSUE THREAD

**Issue by gdoron** [circlecell/jsonlintdotcom#41]
e.g.

jsonlint.com?q={"test": 123}

And it will validate and format the json.

Thanks for the great service!

**Comment by finom** [comment]
@gdoron use ``json`` parameter with urlencoded JSON as value. Example: http://jsonlint.com/?json=%7B%22test%22:%20123%7D

**Comment by gdoron** [comment]
Thanks.
BTW, I whitelisted your website on my adblockers, great service!

**Comment by circlecell** [comment]
Thank you @gdoron :)
