### ISSUE TITLE
Key without quotations

### ISSUE THREAD

**Issue by amaromi** [circlecell/jsonlintdotcom#42]
In javascript it's a legal object to have the key without quotations. Is this something that you can support, maybe as an option?
```
{
	"myNum": [1, 2]
}
```

**Comment by gdoron** [comment]
@amaromi 
But it's **JSON **lint, it should highlight JSON errors...
I think you probably should use jslint (the concept (and library?) jsonlint was based on)

**Comment by finom** [comment]
Yep @amaromi is right. You can look at JSLint.

**Comment by gdoron** [comment]
The very first time I'm right at something and @amaromi gets the credit for that... :stuck_out_tongue_winking_eye:

**Comment by finom** [comment]
Oops :)
