### ISSUE TITLE
Line number mismatch (pro)

### ISSUE THREAD

**Issue by mpf82** [circlecell/jsonlintdotcom#44]
The line numering is off in http://pro.jsonlint.com/

The problem might be browser related, because it only occurs in my Firefox 44.0.2
The same JSON looks fine in my Chrome 39.0.2

End of JSON in text editor:
![2016-02-26 16_10_28-pspad - neu1 txt _](https://cloud.githubusercontent.com/assets/10152404/13356027/9dbb257e-dca3-11e5-93f7-0b1e0305e3cf.png)

End of JSON in Chrome
![2016-02-26 16_10_55-jsonlint pro - the json validator](https://cloud.githubusercontent.com/assets/10152404/13356028/9dbbba52-dca3-11e5-9d1b-7bc071a32579.png)

End of JSON in Firefox
![2016-02-26 16_11_12-jsonlint pro - the json validator](https://cloud.githubusercontent.com/assets/10152404/13356029/9dbda358-dca3-11e5-9508-70c83dffe589.png)

It looks as if the lines are off by a few fractions of a pixel, but if the JSON is large it makes a big difference.

Why not give the textarea and the line div the same font, line height and font size? That would probably make sure the shown lines always match the actual line number.

This might be related to  #18

**Comment by finom** [comment]
Thanks.

**Comment by finom** [comment]
We've made another project [JSONCompare](https://jsoncompare.com/) which is based on community requirements. "pro" version no longer maintained.
