### ISSUE TITLE
Accepting invalid JSON

### ISSUE THREAD

**Issue by mitar** [circlecell/jsonlintdotcom#45]
The following JSON is invalid, but it is accepted by JSONLint:

```json
{
  "@context": {},
  "@id": "id1",
  "@id": "id2",
  "@type": "type1",
  "@type": "type2"
}
```

You can see another validator complaining: http://www.freeformatter.com/json-validator.html

**Comment by mpf82** [comment]
https://www.ietf.org/rfc/rfc4627.txt

    2.2.  Objects
    ... "The names within an object SHOULD be unique."

https://www.ietf.org/rfc/rfc2119.txt

      3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
         may exist valid reasons in particular circumstances to ignore a
         particular item, but the full implications must be understood and
         carefully weighed before choosing a different course.

You can tell the maintainer of the other validator that a JSON with duplicate keys is **not** invalid.

Note: I'm not saying I would recommend the use of duplicate keys, but the specification does not label them as invalid. How an application handles duplicate keys is a different story.
