### ISSUE TITLE
Write jsonlint.manifest

### ISSUE THREAD

**Issue by binki** [circlecell/jsonlintdotcom#5]
If jsonlint is stateless and completely implemented in the client, what is keeping it from enabling itself to be launched offline? Its `<html/>` already even has a `manifest` attribute, suggesting that this was the intention…

**Comment by antonyoneill** [comment]
bump

**Comment by finom** [comment]
This issue is fixed in new version of [jsonlint.com](http://jsonlint.com). Thanks for reporting.
