### ISSUE TITLE
Why is "test" a valid json ?

### ISSUE THREAD

**Issue by TheParad0X** [circlecell/jsonlintdotcom#50]
Hello,
How come "test" is a valid JSON ?
Other validators say it's invalid (as I thought)
Cheers

**Comment by finom** [comment]
Because strings, numbers, booleans and null are valid JSON :) Look at the
spec.
17 Июн 2016 г. 10:25 пользователь "TheParad0X" <notifications@github.com>
написал:

**Comment by fbedussi** [comment]
If I understand the spec (http://www.json.org/) correctly string, number, booleans and null are valid JSON values, not JSON objects per se.

A JSON object must be enclosed in {} and must contain pair(s) of key:value.

So 
````
{"key":"test"}
````
is al valid JSON object, while
````
"test"
````
is not. 

Am I wrong?

**Comment by fbedussi** [comment]
mmm... I double checked the spec and it seems that strings are valid JSON data even if they are not JSON *objects*.
