### ISSUE TITLE
Escaped control characters? 

### ISSUE THREAD

**Issue by dbrb2** [circlecell/jsonlintdotcom#51]
The below: 

{"foo":"foo\nbar"}

Validates in JSONLint

However, if I am reading http://json.org/ correctly, the above is not valid since it contains an unsescaped escape character:

"...any-Unicode-character-except-"-or-\-or-control-character
\" \\ 
\/
\b
\f
\n
\r
\t
\u

Who is right here...?

**Comment by finom** [comment]
This JSON is valid.
