### ISSUE TITLE
Copy/cut with Firefox not working

### ISSUE THREAD

**Issue by thany** [circlecell/jsonlintdotcom#55]
When I copy/cut the validated json in Firefox 48 / Windows 10, pasting it anywhere results in pasting a single `-`.

So even pressing Ctrl+X, Ctrl+V in succession will reduce any code in the code field to a single dash character. Always, valid or not.

**Comment by finom** [comment]
Hmm weird. It's OK on Linux, but I'll check on Windows when I get a chance.

**Comment by finom** [comment]
Unfortunately I cannot reproduce this. Do you have the same issue in other browsers?

**Comment by thany** [comment]
Hm, I just noticed this happening on another website as well.

I do have an option enabled that disables websites from interfering with clipboard functions (courtesy of Youtube) but *normal* copypasting of text and field contents stills work as normal.

On the other hand, I don't have this issue in Edge. But I prefer not use Edge if I can help it 🙂
