### ISSUE TITLE
FAQ - Example URL-Encoded JSON

### ISSUE THREAD

**Issue by jfeltis** [circlecell/jsonlintdotcom#56]
In the FAQ, an example link is provided for testing JSON linting via query string parameters.  The link points to http://www.jsonlint.com/?json=%7B%22hello%22%3A%20%22world%22%7D.  This returns status 404.  However, http://jsonlint.com/?json=%7B%22hello%22%3A%20%22world%22%7D (without www prefix) works as expected.

Possible solution:  nginx configuration for redirecting www to non-www [here](http://stackoverflow.com/questions/7947030/nginx-no-www-to-www-and-www-to-no-www)

**Comment by finom** [comment]
Thank you @jfeltis

**Comment by finom** [comment]
Fixed.
