### ISSUE TITLE
Wrong space in boolean value seems to be valid.

### ISSUE THREAD

**Issue by azakaryan** [circlecell/jsonlintdotcom#59]
This "{\"foo\":t rue}"  evaluates as valid JSON, but it's invalid.

Try  JSON.parse("{\"foo\":t rue}")

**Comment by finom** [comment]
This is simple string and it's valid. You pass valid string to jsonlint but you pass invalid **object** to JSON.parse.

This is the right equivalent using JSON.parse:
```js
JSON.parse("\"{\\\"foo\\\":t rue}\"");
```
