### ISSUE TITLE
Support for large numbers in JSON formatting

### ISSUE THREAD

**Issue by joseph-norman** [circlecell/jsonlintdotcom#60]
Hey guys,

I noticed earlier that supporting large numbers doesn't work ok when I attempt to format JSON (looks to be falling under the JavaScript large numbers arithmetic overflow issue).

Would you accept a PR for this issue?

**Comment by finom** [comment]
@joseph-norman can you show JSON string which causes this issue? Formatting is powered by jsbeautifier and it just adds needed spaces to code (as I know) and doesn't make changes to it.

**Comment by joseph-norman** [comment]
No problem, here's an example I'm using which gets padded with zeroes every time I'm using it:

```
{
    "test field": 7784926383189565243
}
```

**Comment by finom** [comment]
@joseph-norman is it about http://jsonlint.com/ ?

If yes, it works fine for me. Can you make CTRL+Enter and try again?

**Comment by joseph-norman** [comment]
Ah apologies, I'm trying this out on pro.jsonlint.com - is this provided by you guys? It appears to be working ok on jsonlint.com.

**Comment by finom** [comment]
@joseph-norman yes, provided by us but it's not actively maintained.

**Comment by joseph-norman** [comment]
Ah right I see - following from that, would that be something you'd accept a PR for?

**Comment by finom** [comment]
@joseph-norman need to talk to the owner

**Comment by finom** [comment]
@joseph-norman 

> we're working on a newer version and therefore we're not accepting pull requests for that right now

**Comment by joseph-norman** [comment]
Sorry for necro bumping but cheers for the update @finom !
