### ISSUE TITLE
Auto validate/format on change

### ISSUE THREAD

**Issue by Starojitski** [circlecell/jsonlintdotcom#8]
Thanks for the great tool!

i wonder how many people actually type their json strings to validate them and how many paste strings from some other source either to validate them or properly indent them ? For the latter, clicking on validate button every time becomes repetitive pretty quickly...

Autovalidation would be really welcome! Or at least a keyboard shortcut

Thanks in advance

**Comment by finom** [comment]
@Starojitski I think this will cause UX problems for some users. The best way to get rid of clicks is to use Ctrl+Enter. What do you think?


@circlecell do we need to add another URL parameter called "autovalidate"? Eg
```
jsonlint.com/?autovalidate=yes
```

**Comment by Starojitski** [comment]
After thinking about it for a while, the fastest is to have one big button at the top of the screen: 'Validate and Format clipboard'.
As the name suggests, clicking on that button pastes clipboard contents into the text area, triggers validation and immediately copies and pastes the text area content into clipboard... Just one click!
And if this button has `autofocus` attribute it would make it just one one Enter or Space keypress for keyboard us

**Comment by Starojitski** [comment]
My apologies, i pressed the wrong button and by mistake closed issue

I was thinking about it and i thought the fastest way would be to have one button called 'Format Clipboard' that would do everything: pasting clipboard into the text area, validating json and, if it's valid, copying formatted version into clipboard. If that button is largish and near the top center of the screen it would be easy to click. Setting `autofocus` on that button make it ideal for keyboard use - just one Enter or Space press! 
Unfortunately, while writing to clipboard is possible in all modern browsers, reading from it seems impossible. Correct me if i am wrong

**Comment by finom** [comment]
@Starojitski thanks for your ideas. The main goal for us is to keep jsonlint.com as simple as possible. That's why it's used by millions of people from all over the world. I don't think that adding extra buttons is good idea.

You can use shortcuts for your goal:
- Ctrl + V to paste your code
- Ctrl + Enter to run validation
- Ctrl + A to select formatted code
- Ctrl + C to copy it to your clipboard
