### ISSUE TITLE
Double in Json lint get truncated or Errors out on extra 0s

### ISSUE THREAD

**Issue by akku-dangeR** [circlecell/jsonlintdotcom#9]
Example:
//truncat
{
    "x": 0.100
}
//error
{
    "x": 001
}

Also observed in Pro.

**Comment by finom** [comment]
The first issue is fixed in new version of [jsonlint.com](http://jsonlint.com). The second isn't an issue. 

Try this code:
```js
JSON.parse('001'); // Uncaught SyntaxError: Unexpected number
```

Thanks for reporting.
